---
# tasks file for postgresql-default
- name: install package
  package:
    name: "postgresql-{{postgresql_version}}"
    state: present
- name: provide custom hba
  template:
    src: templates/pg_hba_custom.conf.j2
    dest: "{{postgres_confd_path}}/../pg_hba_custom.conf"
    owner: postgres
    group: postgres
#- include_tasks: shared_preload_libraries.yml
- include_tasks: install_fact_script.yml
- include_tasks: check_preload_libraries.yml
- name: provide default config
  template:
    src: templates/00-default.conf.j2
    dest: "{{postgres_confd_path}}/00-default.conf"
    owner: postgres
    group: postgres
  notify: postgres_restart
- name: "ensure backup directory exists"
  file:
    path: /backup
    state: directory
- name: "create backup of database to /backup"
  cron:
      #cron_file: undefined # not required. If specified, uses this file instead of an individual user's crontab. If this is a relative path, it is interpreted with respect to /etc/cron.d. (If it is absolute, it will typically be /etc/crontab). Many linux distros expect (and some require) the filename portion to consist solely of upper- and lower-case letters, digits, underscores, and hyphens. To use the C(cron_file) parameter you must specify the C(user) as well.
      month: "*" # not required. Month of the year the job should run ( 1-12, *, */2, etc )
      #disabled: no # not required. If the job should be disabled (commented out) in the crontab.,Only has effect if C(state=present).
      job: "pg_dumpall -Upostgres -h 127.0.0.1 -Fc > /backup/whole_db.dump" # not required. The command to execute or, if env is set, the value of environment variable. The command should not contain line breaks. Required if state=present.
      #special_time: reboot # not required. choices: reboot;yearly;annually;monthly;weekly;daily;hourly. Special time specification nickname.
      user: root # not required. The specific user whose crontab should be modified.
      #insertafter: undefined # not required. Used with C(state=present) and C(env). If specified, the environment variable will be inserted after the declaration of specified environment variable.
      #insertbefore: undefined # not required. Used with C(state=present) and C(env). If specified, the environment variable will be inserted before the declaration of specified environment variable.
      day: "*" # not required. Day of the month the job should run ( 1-31, *, */2, etc )
      minute: 0 # not required. Minute when the job should run ( 0-59, *, */2, etc )
      #name: undefined # not required. Description of a crontab entry or, if env is set, the name of environment variable. Required if state=absent. Note that if name is not set and state=present, then a new crontab entry will always be created, regardless of existing ones.
      hour: 1 # not required. Hour when the job should run ( 0-23, *, */2, etc )
      #reboot: no # not required. If the job should be run at reboot. This option is deprecated. Users should use special_time.
      state: present # not required. choices: absent;present. Whether to ensure the job or environment variable is present or absent.
      #weekday: * # not required. Day of the week that the job should run ( 0-6 for Sunday-Saturday, *, etc )
      #env: no # not required. If set, manages a crontab's environment variable. New variables are added on top of crontab. "name" and "value" parameters are the name and the value of environment variable.
      #backup: no # not required. If set, create a backup of the crontab before it is modified. The location of the backup is returned in the C(backup_file) variable by this module.
- name: "copy backup of whole database to s3"
  cron:
      #cron_file: undefined # not required. If specified, uses this file instead of an individual user's crontab. If this is a relative path, it is interpreted with respect to /etc/cron.d. (If it is absolute, it will typically be /etc/crontab). Many linux distros expect (and some require) the filename portion to consist solely of upper- and lower-case letters, digits, underscores, and hyphens. To use the C(cron_file) parameter you must specify the C(user) as well.
      month: "*" # not required. Month of the year the job should run ( 1-12, *, */2, etc )
      #disabled: no # not required. If the job should be disabled (commented out) in the crontab.,Only has effect if C(state=present).
      job: "aws --endpoint-url http://192.168.178.17:9000 s3 cp /backup/whole_db.dump s3://backups/postgres/{{ansible_hostname}}/" # not required. The command to execute or, if env is set, the value of environment variable. The command should not contain line breaks. Required if state=present.
      #special_time: reboot # not required. choices: reboot;yearly;annually;monthly;weekly;daily;hourly. Special time specification nickname.
      user: root # not required. The specific user whose crontab should be modified.
      #insertafter: undefined # not required. Used with C(state=present) and C(env). If specified, the environment variable will be inserted after the declaration of specified environment variable.
      #insertbefore: undefined # not required. Used with C(state=present) and C(env). If specified, the environment variable will be inserted before the declaration of specified environment variable.
      day: "*" # not required. Day of the month the job should run ( 1-31, *, */2, etc )
      minute: 5 # not required. Minute when the job should run ( 0-59, *, */2, etc )
      #name: undefined # not required. Description of a crontab entry or, if env is set, the name of environment variable. Required if state=absent. Note that if name is not set and state=present, then a new crontab entry will always be created, regardless of existing ones.
      hour: 1 # not required. Hour when the job should run ( 0-23, *, */2, etc )
      #reboot: no # not required. If the job should be run at reboot. This option is deprecated. Users should use special_time.
      state: present # not required. choices: absent;present. Whether to ensure the job or environment variable is present or absent.
      #weekday: * # not required. Day of the week that the job should run ( 0-6 for Sunday-Saturday, *, etc )
      #env: no # not required. If set, manages a crontab's environment variable. New variables are added on top of crontab. "name" and "value" parameters are the name and the value of environment variable.
      #backup: no # not required. If set, create a backup of the crontab before it is modified. The location of the backup is returned in the C(backup_file) variable by this module.
