- name: provide shared_preload_libraries config
  template:
    src: templates/01-shared_preload_libraries.conf.j2
    dest: "{{postgres_confd_path}}/01-shared_preload_libraries.conf"
    owner: postgres
    group: postgres
- name: try to collect facts
  shell: "psql -Upostgres -h127.0.0.1 -P pager=off -t -c \"select concat('\"',r.name,'\" : \"',r.setting,'\"') from (select name, setting from pg_settings) as r;\""
  register: pg_result
- set_fact: 
    pg_settings: "{{pg_result}}"