---
# defaults file for nginx-awx
nginx_default_server_name: "{{ansible_host}}"
nginx_conf_path: "/etc/nginx/nginx.conf"
nginx_sites_available: "/etc/nginx/sites-available"
nginx_sites_enabled: "/etc/nginx/sites-enabled"
awx_port: 81
awx:
  domain_name: "{{ansible_host}}"
  upstream: "127.0.0.1"
ssl_available:
  key_name: privkey.pem
  fullchain_name: fullchain.pem