---
- name: install python3-pymysql
  apt:
    pkg: python3-pymysql
    state: present
- name: install python-pymysql
  apt:
    pkg: python-pymysql
    state: present
- name: install mysql client
  apt:
    pkg: mariadb-client-core-10.1
    state: present
- name: install pip prerequisites
  pip:
      #virtualenv: undefined # not required. An optional path to a I(virtualenv) directory to install into. It cannot be specified together with the 'executable' parameter (added in 2.1). If the virtualenv does not exist, it will be created before installing packages. The optional virtualenv_site_packages, virtualenv_command, and virtualenv_python options affect the creation of the virtualenv.
      #virtualenv_site_packages: no # not required. Whether the virtual environment will inherit packages from the global site-packages directory.  Note that if this setting is changed on an already existing virtual environment it will not have any effect, the environment must be deleted and newly created.
      #virtualenv_command: virtualenv # not required. The command or a pathname to the command to create the virtual environment with. For example C(pyvenv), C(virtualenv), C(virtualenv2), C(~/bin/virtualenv), C(/usr/local/bin/virtualenv).
      #chdir: undefined # not required. cd into this directory before running the command
      #requirements: undefined # not required. The path to a pip requirements file, which should be local to the remote system. File can be specified as a relative path if using the chdir option.
      name: PyMySQL # not required. The name of a Python library to install or the url(bzr+,hg+,git+,svn+) of the remote package.,This can be a list (since 2.2) and contain version specifiers (since 2.7).
      #virtualenv_python: undefined # not required. The Python executable used for creating the virtual environment. For example C(python3.5), C(python2.7). When not specified, the Python version used to run the ansible module is used. This parameter should not be used when C(virtualenv_command) is using C(pyvenv) or the C(-m venv) module.
      #editable: no # not required. Pass the editable flag.
      #umask: undefined # not required. The system umask to apply before installing the pip package. This is useful, for example, when installing on systems that have a very restrictive umask by default (e.g., 0077) and you want to pip install packages which are to be used by all users. Note that this requires you to specify desired umask mode in octal, with a leading 0 (e.g., 0077).
      executable: pip3 # not required. The explicit executable or a pathname to the executable to be used to run pip for a specific version of Python installed in the system. For example C(pip-3.3), if there are both Python 2.7 and 3.3 installations in the system and you want to run pip for the Python 3.3 installation. It cannot be specified together with the 'virtualenv' parameter (added in 2.1). By default, it will take the appropriate version for the python interpreter use by ansible, e.g. pip3 on python 3, and pip2 or pip on python 2.
      #extra_args: undefined # not required. Extra arguments passed to pip.
      state: present # not required. choices: absent;forcereinstall;latest;present. The state of module,The 'forcereinstall' option is only available in Ansible 2.1 and above.
      #version: undefined # not required. The version number to install of the Python library specified in the I(name) parameter.
- name: "get ~{{zbx_server_shell_user_name}}"
  stat:
    path: "~{{zbx_server_shell_user_name}}"
  tags:
    - "test"
  register: zabbix_home
- name: get environmment path
  set_fact:
    environment_path: "{{zabbix_home.stat.path}}"
  tags:
    - "test"
#- name: create Database
#  mysql_db:
#    name: "{{ zbx_db_name }}"
#    encoding: utf8
#    state: present
#    login_port: 3306 # not required. Port of the MySQL server. Requires I(login_host) be defined as other then localhost if login_port is used.
#    login_user: "{{zbx_db_user}}" # not required. The username used to authenticate with.
#    login_host: "{{zbx_db_host}}" # not required. Host running the database.
#    login_password: "{{zbx_db_password}}" # not required. The password used to authenticate with.
#    #ssl_key: undefined # not required. The path to the client private key.
#    #ssl_ca: undefined # not required. The path to a Certificate Authority (CA) certificate. This option, if used, must specify the same certificate as used by the server.
#    #collation: undefined # not required. Collation mode (sorting). This only applies to new table/databases and does not update existing ones, this is a limitation of MySQL.
#    #ignore_tables:  # not required. A list of table names that will be ignored in the dump of the form database_name.table_name
#    #quick: yes # not required. Option used for dumping large tables
#    #single_transaction: no # not required. Execute the dump in a single transaction
#    #connect_timeout: 30 # not required. The connection timeout when connecting to the MySQL server.
#  register: database
    
- name: Import Schema
  mysql_db:
    state: import
    login_port: 3306 # not required. Port of the MySQL server. Requires I(login_host) be defined as other then localhost if login_port is used.
    login_user: "{{zbx_db_user}}" # not required. The username used to authenticate with.
    login_host: "{{zbx_db_host}}" # not required. Host running the database.
    login_password: "{{zbx_db_password}}" # not required. The password used to authenticate with.
    name: "{{ zbx_db_name }}"
    target: "{{ environment_path }}/src/database/mysql/schema.sql"
  register: import_result
  ignore_errors: yes
- name: output import results
  debug: 
    msg: "{{import_result}}"
    
- name: Import images
  mysql_db:
    state: import
    login_port: 3306 # not required. Port of the MySQL server. Requires I(login_host) be defined as other then localhost if login_port is used.
    login_user: "{{zbx_db_user}}" # not required. The username used to authenticate with.
    login_host: "{{zbx_db_host}}" # not required. Host running the database.
    login_password: "{{zbx_db_password}}" # not required. The password used to authenticate with.
    name: "{{ zbx_db_name }}"
    target: "{{ environment_path }}/src/database/mysql/images.sql"
  when: "'ERROR' not in import_result"
  ignore_errors: yes
  tags: 
    - Install
    
- name: Import data
  mysql_db:
    state: import
    login_port: 3306 # not required. Port of the MySQL server. Requires I(login_host) be defined as other then localhost if login_port is used.
    login_user: "{{zbx_db_user}}" # not required. The username used to authenticate with.
    login_host: "{{zbx_db_host}}" # not required. Host running the database.
    login_password: "{{zbx_db_password}}" # not required. The password used to authenticate with.
    name: "{{ zbx_db_name }}"
    target: "{{ environment_path }}/src/database/mysql/data.sql"
  when: "'ERROR' not in import_result"
  ignore_errors: yes
  tags: 
    - Install