- include_tasks: removedefaultpass.yml
- name: Authenticate with Zabbix API
  uri:
    url: "{{zabbix_api_url}}/api_jsonrpc.php"
    method: POST
    body: "{ \"jsonrpc\": \"2.0\", \"method\" : \"user.login\", \"params\": { \"user\": {{zabbix_api_user|tojson}}, \"password\": {{zabbix_api_pass|tojson}}}, \"id\": 1 }"
    body_format: json
    return_content: yes
  register: json_response 
- name: check for error
  set_fact: 
    auth_error: "{{((json_response.content|from_json)['error']['data'])| default('')}}"
- name: output auth_error variable
  debug:
    msg: "{{auth_error}}"
#- name: output auth variable
#  debug:
#    msg: "{{json_response}}"
- name: "Registering Zabbix API Auth Token"
  set_fact:
    ZABAPIAUTH: "{{(json_response.content|from_json)['result']}}"
  when: auth_error == ""
- include_tasks: authed.yml
  when: auth_error == ""