all:
  hosts:
    postgresql.novalocal:
      ansible_user: "ubuntu"
      ansible_port: "22"
      ansible_host: "192.168.178.206"
      
  children:
    bootstrap:
      hosts:
        postgresql.novalocal: