all:
  hosts:
    dynamic192.novalocal: 
      ansible_user: "ubuntu"
      ansible_port: "22"
      ansible_host: "192.168.178.192"
    dynamic193.novalocal: 
      ansible_user: "ubuntu"
      ansible_port: "22"
      ansible_host: "192.168.178.193"
    dynamic194.novalocal: 
      ansible_user: "ubuntu"
      ansible_port: "22"
      ansible_host: "192.168.178.194"
    dynamic195.novalocal: 
      ansible_user: "ubuntu"
      ansible_port: "22"
      ansible_host: "192.168.178.195"
    dynamic196.novalocal: 
      ansible_user: "ubuntu"
      ansible_port: "22"
      ansible_host: "192.168.178.196"
    dynamic197.novalocal: 
      ansible_user: "ubuntu"
      ansible_port: "22"
      ansible_host: "192.168.178.197"
    dynamic198.novalocal: 
      ansible_user: "ubuntu"
      ansible_port: "22"
      ansible_host: "192.168.178.198"
    dynamic199.novalocal: 
      ansible_user: "ubuntu"
      ansible_port: "22"
      ansible_host: "192.168.178.199"
    dynamic200.novalocal: 
      ansible_user: "ubuntu"
      ansible_port: "22"
      ansible_host: "192.168.178.200"
    dynamic201.novalocal: 
      ansible_user: "ubuntu"
      ansible_port: "22"
      ansible_host: "192.168.178.201"
    dynamic202.novalocal: 
      ansible_user: "ubuntu"
      ansible_port: "22"
      ansible_host: "192.168.178.202"
    dynamic203.novalocal: 
      ansible_user: "ubuntu"
      ansible_port: "22"
      ansible_host: "192.168.178.203"
    dynamic204.novalocal: 
      ansible_user: "ubuntu"
      ansible_port: "22"
      ansible_host: "192.168.178.204"
    dynamic205.novalocal: 
      ansible_user: "ubuntu"
      ansible_port: "22"
      ansible_host: "192.168.178.205"
    dynamic206.novalocal: 
      ansible_user: "ubuntu"
      ansible_port: "22"
      ansible_host: "192.168.178.206"
    dynamic207.novalocal: 
      ansible_user: "ubuntu"
      ansible_port: "22"
      ansible_host: "192.168.178.207"
    dynamic208.novalocal: 
      ansible_user: "ubuntu"
      ansible_port: "22"
      ansible_host: "192.168.178.208"
    dynamic209.novalocal: 
      ansible_user: "ubuntu"
      ansible_port: "22"
      ansible_host: "192.168.178.209"
    dynamic210.novalocal: 
      ansible_user: "ubuntu"
      ansible_port: "22"
      ansible_host: "192.168.178.210"
    dynamic211.novalocal: 
      ansible_user: "ubuntu"
      ansible_port: "22"
      ansible_host: "192.168.178.211"
    dynamic212.novalocal: 
      ansible_user: "ubuntu"
      ansible_port: "22"
      ansible_host: "192.168.178.212"
    dynamic213.novalocal: 
      ansible_user: "ubuntu"
      ansible_port: "22"
      ansible_host: "192.168.178.213"
    dynamic214.novalocal: 
      ansible_user: "ubuntu"
      ansible_port: "22"
      ansible_host: "192.168.178.214"
    dynamic215.novalocal: 
      ansible_user: "ubuntu"
      ansible_port: "22"
      ansible_host: "192.168.178.215"
    dynamic216.novalocal: 
      ansible_user: "ubuntu"
      ansible_port: "22"
      ansible_host: "192.168.178.216"
    dynamic217.novalocal: 
      ansible_user: "ubuntu"
      ansible_port: "22"
      ansible_host: "192.168.178.217"
    dynamic218.novalocal: 
      ansible_user: "ubuntu"
      ansible_port: "22"
      ansible_host: "192.168.178.218"
    dynamic219.novalocal: 
      ansible_user: "ubuntu"
      ansible_port: "22"
      ansible_host: "192.168.178.219"
    dynamic220.novalocal: 
      ansible_user: "ubuntu"
      ansible_port: "22"
      ansible_host: "192.168.178.220"
    dynamic222.novalocal: 
      ansible_user: "ubuntu"
      ansible_port: "22"
      ansible_host: "192.168.178.222"
    dynamic223.novalocal: 
      ansible_user: "ubuntu"
      ansible_port: "22"
      ansible_host: "192.168.178.223"
    dynamic224.novalocal: 
      ansible_user: "ubuntu"
      ansible_port: "22"
      ansible_host: "192.168.178.224"
    dynamic225.novalocal: 
      ansible_user: "ubuntu"
      ansible_port: "22"
      ansible_host: "192.168.178.225"
    dynamic226.novalocal: 
      ansible_user: "ubuntu"
      ansible_port: "22"
      ansible_host: "192.168.178.226"
    dynamic227.novalocal: 
      ansible_user: "ubuntu"
      ansible_port: "22"
      ansible_host: "192.168.178.227"
    dynamic228.novalocal: 
      ansible_user: "ubuntu"
      ansible_port: "22"
      ansible_host: "192.168.178.228"
    dynamic229.novalocal: 
      ansible_user: "ubuntu"
      ansible_port: "22"
      ansible_host: "192.168.178.229"
    dynamic230.novalocal: 
      ansible_user: "ubuntu"
      ansible_port: "22"
      ansible_host: "192.168.178.230"       
  children:
    postgres:
      hosts:
        dynamic215.novalocal:
    timescaledb:
      hosts:
        dynamic209.novalocal:
    mysql:
      hosts:
        dynamic200.novalocal: 
    zabbix:
      hosts:
        dynamic000.novalocal:
    bootstrap:
      children:
        subgroup1:
          hosts:
            dynamic230.novalocal: 
        subgroup2:
          hosts:
            dynamic229.novalocal: 
      hosts:
        dynamic215.novalocal: