all:
  hosts:
    192.novalocal: 
      ansible_user: ubuntu
      ansible_port: 22
      ansible_host: 192.168.178.192
    193.novalocal: 
      ansible_user: ubuntu
      ansible_port: 22
      ansible_host: 192.168.178.193
    194.novalocal: 
      ansible_user: ubuntu
      ansible_port: 22
      ansible_host: 192.168.178.194
    195.novalocal: 
      ansible_user: ubuntu
      ansible_port: 22
      ansible_host: 192.168.178.195
    196.novalocal: 
      ansible_user: ubuntu
      ansible_port: 22
      ansible_host: 192.168.178.196
    197.novalocal: 
      ansible_user: ubuntu
      ansible_port: 22
      ansible_host: 192.168.178.197
    198.novalocal: 
      ansible_user: ubuntu
      ansible_port: 22
      ansible_host: 192.168.178.198
    199.novalocal: 
      ansible_user: ubuntu
      ansible_port: 22
      ansible_host: 192.168.178.199
    200.novalocal: 
      ansible_user: ubuntu
      ansible_port: 22
      ansible_host: 192.168.178.200
    201.novalocal: 
      ansible_user: ubuntu
      ansible_port: 22
      ansible_host: 192.168.178.201
    202.novalocal: 
      ansible_user: ubuntu
      ansible_port: 22
      ansible_host: 192.168.178.202
    203.novalocal: 
      ansible_user: ubuntu
      ansible_port: 22
      ansible_host: 192.168.178.203
    204.novalocal: 
      ansible_user: ubuntu
      ansible_port: 22
      ansible_host: 192.168.178.204
    205.novalocal: 
      ansible_user: ubuntu
      ansible_port: 22
      ansible_host: 192.168.178.205
    206.novalocal: 
      ansible_user: ubuntu
      ansible_port: 22
      ansible_host: 192.168.178.206
    207.novalocal: 
      ansible_user: ubuntu
      ansible_port: 22
      ansible_host: 192.168.178.207
    208.novalocal: 
      ansible_user: ubuntu
      ansible_port: 22
      ansible_host: 192.168.178.208
    209.novalocal: 
      ansible_user: ubuntu
      ansible_port: 22
      ansible_host: 192.168.178.209
    210.novalocal: 
      ansible_user: ubuntu
      ansible_port: 22
      ansible_host: 192.168.178.210
    211.novalocal: 
      ansible_user: ubuntu
      ansible_port: 22
      ansible_host: 192.168.178.211
    212.novalocal: 
      ansible_user: ubuntu
      ansible_port: 22
      ansible_host: 192.168.178.212
    213.novalocal: 
      ansible_user: ubuntu
      ansible_port: 22
      ansible_host: 192.168.178.213
    214.novalocal: 
      ansible_user: ubuntu
      ansible_port: 22
      ansible_host: 192.168.178.214
    215.novalocal: 
      ansible_user: ubuntu
      ansible_port: 22
      ansible_host: 192.168.178.215
    216.novalocal: 
      ansible_user: ubuntu
      ansible_port: 22
      ansible_host: 192.168.178.216
    217.novalocal: 
      ansible_user: ubuntu
      ansible_port: 22
      ansible_host: 192.168.178.217
    218.novalocal: 
      ansible_user: ubuntu
      ansible_port: 22
      ansible_host: 192.168.178.218
    219.novalocal: 
      ansible_user: ubuntu
      ansible_port: 22
      ansible_host: 192.168.178.219
    220.novalocal: 
      ansible_user: ubuntu
      ansible_port: 22
      ansible_host: 192.168.178.220
    #221.novalocal:  # awx
    #  ansible_user: ubuntu
    #  ansible_port: 22
    #  ansible_host: 192.168.178.221
    222.novalocal: 
      ansible_user: ubuntu
      ansible_port: 22
      ansible_host: 192.168.178.222
    223.novalocal: 
      ansible_user: ubuntu
      ansible_port: 22
      ansible_host: 192.168.178.223
    224.novalocal: 
      ansible_user: ubuntu
      ansible_port: 22
      ansible_host: 192.168.178.224
    225.novalocal: 
      ansible_user: ubuntu
      ansible_port: 22
      ansible_host: 192.168.178.225
    226.novalocal: 
      ansible_user: ubuntu
      ansible_port: 22
      ansible_host: 192.168.178.226
    227.novalocal: 
      ansible_user: ubuntu
      ansible_port: 22
      ansible_host: 192.168.178.227
    228.novalocal: 
      ansible_user: ubuntu
      ansible_port: 22
      ansible_host: 192.168.178.228
    229.novalocal: 
      ansible_user: ubuntu
      ansible_port: 22
      ansible_host: 192.168.178.229
    230.novalocal: 
      ansible_user: ubuntu
      ansible_port: 22
      ansible_host: 192.168.178.230

       
  children:
    postgres:
      hosts:
        215.novalocal:
    bootstrap:
      hosts:
        all: