---
- name: "Overwrite Default basedir of {{basedir}}"
  set_fact:
    basedir: "/mnt/c/Users/Hackspace/Documents/GitHub/awx-provisioner"
- name: Create Initial Folder Structure
  file:
    path: "{{basedir}}/{{item_dir}}" # required. Path to the file being managed.
    #group: undefined # not required. Name of the group that should own the file/directory, as would be fed to I(chown).
    state: directory # not required. choices: absent;directory;file;hard;link;touch. If C(directory), all intermediate subdirectories will be created if they do not exist. Since Ansible 1.7 they will be created with the supplied permissions. If C(file), the file will NOT be created if it does not exist; see the C(touch) value or the M(copy) or M(template) module if you want that behavior.  If C(link), the symbolic link will be created or changed. Use C(hard) for hardlinks. If C(absent), directories will be recursively deleted, and files or symlinks will be unlinked. Note that C(absent) will not cause C(file) to fail if the C(path) does not exist as the state did not change. If C(touch) (new in 1.4), an empty file will be created if the C(path) does not exist, while an existing file or directory will receive updated file access and modification times (similar to the way `touch` works from the command line).
    #mode: undefined # not required. Mode the file or directory should be. For those used to I(/usr/bin/chmod) remember that modes are actually octal numbers. You must either add a leading zero so that Ansible's YAML parser knows it is an octal number (like C(0644) or C(01777)) or quote it (like C('644') or C('1777')) so Ansible receives a string and can do its own conversion from string into number.  Giving Ansible a number without following one of these rules will end up with a decimal number which will have unexpected results. As of version 1.8, the mode may be specified as a symbolic mode (for example, C(u+rwx) or C(u=rw,g=r,o=r)).
    #owner: undefined # not required. Name of the user that should own the file/directory, as would be fed to I(chown).
    #follow: yes # not required. This flag indicates that filesystem links, if they exist, should be followed.,Previous to Ansible 2.5, this was C(no) by default.    
  with_items:
    - "inventory"
    - "roles"
  loop_control:
    loop_var: item_dir
- include_tasks: itter_inventories.yml
  with_items:
    - "production"
    - "staging"
    - "development"
  loop_control:
    loop_var: inventory_name